name: hashcode
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.0+1
  firebase_database: ^6.0.0
  liquid_progress_indicator: ^0.3.2
  smooth_page_indicator: ^0.2.0
  rounded_loading_button: ^1.0.0
  url_launcher: ^5.7.10
  data_connection_checker: ^0.3.4
  flutter_restart: ^0.0.3
  sqflite: ^1.3.2+3
  path_provider: ^1.6.27
  flutter_spinkit: "^4.1.2"
  flutter_launcher_icons: ^0.8.1
  loading_animations: "^2.1.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logo.png"
  image_path_android: "assets/images/logo.png"
  adaptive_icon_background: "assets/images/logo_bg.png"
  adaptive_icon_foreground: "assets/images/logo_fg.png"



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/levels/square.png
    - assets/images/dsc_logo.png
    - assets/images/levels/coins.png
    - assets/images/caution.png
    - assets/images/hump.png
    - assets/images/login/username.png
    - assets/images/login/password.png
    - assets/images/login/hash.png
    - assets/images/login/google.png
    - assets/images/login/facebook.png
    - assets/images/login/github.png
    - assets/images/register/email.png
    - assets/images/register/key.png
    - assets/images/profile/level0.png
    - assets/images/profile/level1.png
    - assets/images/profile/level2.png
    - assets/images/profile/level3.png
    - assets/images/profile/level4.png
    - assets/images/profile/level5.png
    - assets/images/profile/solution.png
    - assets/images/profile/score.png
    - assets/images/profile/rank.png
    - assets/images/about/meriem.jpg
    - assets/images/about/aziz.jpg
    - assets/images/about/aaron.jpg
    - assets/images/lvl_list/true.png
    - assets/images/lvl_list/false.png
    - assets/images/problems/caution.png
    - assets/images/problems/cong.png
    - assets/images/social/linkedin.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Product Sans
      fonts:
        - asset: assets/fonts/Product Sans Regular.ttf
        - asset: assets/fonts/Product Sans Bold Italic.ttf
          style: italic 
          weight: 700
        - asset: assets/fonts/Product Sans Bold.ttf
          weight: 700
        - asset: assets/fonts/Product Sans Italic.ttf
          style: italic
    - family: Input
      fonts:
        - asset: assets/fonts/InputSans-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
